Fix issue #6
ffpp2003/SAPEICore pull request #26
Opened 2024-10-25 15:09 UTC by Ignagx

Close #6

2024-10-25 15:10 UTC, Ignagx commented
Falta implementar al pedir los datos de un cliente, que complete con los datos de todos lo vehiculos

2024-10-25 15:56 UTC, Corte0 commented
habría que implementar un método para eliminar el Vehículo por la patente además de por el índice.

2024-10-25 16:03 UTC, Corte0 commented on Vehicle.h
> +    Vehicle();
Esto para que se agregó?

2024-10-25 16:04 UTC, Ignagx commented on Vehicle.h
> +    Vehicle();
Es el constructor de copia

2024-10-25 16:30 UTC, Corte0 commented
Otra cosa, estos cambios hacen que la clase DataBase no compile. tenes que modificar las clases que dependen de esta para que funcionen tambien

2024-10-25 17:37 UTC, Corte0 commented on Vehicle.h
> +    Vehicle();
eso no es un constructor de copia
el constructor de copia deberia pedir un objeto vehicle por referencia
no esta haciendo nada esa linea para mi

2024-10-25 17:53 UTC, Ignagx commented on Vehicle.h
> +    Vehicle();
Ok, pense que eran equivalentes

2024-10-25 19:56 UTC, Corte0 commented on Client.h
> -    void removeVehicleByPos(int vehiclePos);
me gusta que devuelva un valor, le agregaría que devuelva un codigo de error de vehiculo no encontrado, deberias agregar el codigo de derror a Error.h.
tambien deberias implementar lo mismo en el metodo que obtiene por patente

2024-10-25 20:54 UTC, Ignagx commented on Client.h
> -    void removeVehicleByPos(int vehiclePos);
Doing

2024-10-25 21:01 UTC, Ignagx commented on Client.h
> -    void removeVehicleByPos(int vehiclePos);
Done

2024-10-26 02:28 UTC, Corte0 requested changes

2024-10-26 02:28 UTC, Corte0 commented on Client.cpp
>      vehicleFound = 1;
Debería devolver 0 si no hay error

2024-10-26 02:28 UTC, Corte0 commented on Error.h
>          //CLIENT_ERROR  [100 - 199]
Estos errores son del otro cliente, el que esta haciendo gaston, no de la clase. Esta feo ? si
pero tampoco se en que categoria pondria el error.

2024-10-26 02:28 UTC, Corte0 commented on main.cpp
che culia

2024-10-26 02:28 UTC, Corte0 commented on SAPEI.db
why, just why.

2024-10-26 02:28 UTC, Corte0 commented on miPrograma
T-T

2024-10-26 02:28 UTC, Corte0 reviewed
nais

2024-10-26 02:29 UTC, Ignagx commented on Client.cpp
>      vehicleFound = 1;
okok ahi lo cambio

2024-10-26 02:41 UTC, Ignagx commented on Error.h
>          //CLIENT_ERROR  [100 - 199]
Pero lo cambio, lo dejo asi? que lo resuelva gaston jkasjas

2024-10-26 23:52 UTC, gaston1709 reviewed
Saca el SAPEI.db del commit

2024-10-26 23:53 UTC, gaston1709 requested changes
sacar el SAPEI.db del commit

2024-10-27 00:00 UTC, gaston1709 approved these changes

2024-10-27 01:08 UTC, gaston1709 approved these changes

2024-10-27 12:13 UTC, Corte0 requested changes

2024-10-27 12:13 UTC, Corte0 commented on Client.cpp
> +    std::string vehiculos;
Esta variable no se usa

2024-10-27 12:13 UTC, Corte0 commented on DataBase.cpp
> +            client.addVehicle(vehicle);  // Assuming Client has an addVehicle() method
Borrar este comentario

2024-10-27 12:17 UTC, Corte0 approved these changes

2024-10-27 12:17 UTC, merged