Fix issue #4
ffpp2003/SAPEICore pull request #7
Opened 2024-10-20 22:01 UTC by Corte0

2024-10-20 22:01 UTC, Corte0 commented
problema @ffpp2003

2024-10-21 02:31 UTC, Corte0 commented
aqui no pasó nada señor @ffpp2003

2024-10-22 01:45 UTC, fpp3 approved these changes

2024-10-22 02:53 UTC, ffpp2003 requested changes
documentaciooooooooon

2024-10-22 11:59 UTC, gaston1709 requested changes, later dismissed
el export csv porfiwis

2024-10-22 20:23 UTC, Corte0 commented
El export csv se va a dejar como issue para desarrollar mas adelante

2024-10-22 20:33 UTC, ffpp2003 approved these changes

2024-10-22 20:33 UTC, merged